# Generated by Django 5.2.8 on 2025-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('username', models.CharField(help_text='Например: @notcoin_bot', max_length=100, unique=True)),
                ('telegram_url', models.URLField(verbose_name='Ссылка на бота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание (для карточек)')),
                ('icon_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на иконку')),
                ('category', models.CharField(choices=[('DeFi', 'DeFi'), ('Game', 'Game'), ('Social', 'Social'), ('Utility', 'Utility'), ('Marketplace', 'Marketplace')], max_length=50, verbose_name='Категория')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('users_count', models.CharField(default='N/A', max_length=50, verbose_name='Кол-во пользователей')),
                ('is_hero', models.BooleanField(default=False, verbose_name='🔥 Показать в Hero (Главный баннер)')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='🏆 Приложение недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
