# Generated by Django 5.2.8 on 2025-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramapp',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка (Файл)'),
        ),
    ]
