# Generated by Django 5.2.8 on 2025-12-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0002_remove_telegramapp_icon_url_telegramapp_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка (slug)')),
                ('icon_emoji', models.CharField(blank=True, max_length=10, verbose_name='Иконка (эмодзи)')),
                ('color_theme', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=20, verbose_name='Цветовая тема')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='category',
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='users_count',
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='version',
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='users_count_str',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Кол-во пользователей (текст)'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткое описание'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(verbose_name='URL-метка (slug)')),
                ('icon_emoji', models.CharField(blank=True, max_length=10, verbose_name='Иконка (эмодзи)')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='apps_store.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='apps_store.subcategory', verbose_name='Подкатегория'),
        ),
    ]
