# Generated by Django 5.2.8 on 2025-12-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0003_category_remove_telegramapp_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telegramapp',
            options={},
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='telegramapp',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='affiliate_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Full Desc (EN)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Полное (RU)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='has_affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='is_ai_processed',
            field=models.BooleanField(default=False, verbose_name='🤖 Обработано ИИ'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Desc (EN)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое (RU)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='telegramapp',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_theme',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (Техническое)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='apps_store.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='apps_store.subcategory'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='telegram_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='users_count_str',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
