# Generated by Django 5.2.8 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0004_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='telegramapp',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='affiliate_status',
            field=models.CharField(choices=[('pending', '⏳ Ожидание'), ('connected', '✅ Подключена'), ('manual', '🛠 Вручную'), ('none', '❌ Нет')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Desc (EN)'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='is_ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
