# Generated by Django 5.2.8 on 2025-12-05 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0006_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Контент (EN)')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, verbose_name='Контент (RU)')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Обложка')),
                ('category', models.CharField(default='Guide', max_length=50, verbose_name='Тег (Guide, News...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': '📰 Новости и Статьи',
            },
        ),
        migrations.CreateModel(
            name='HeroAppProxy',
            fields=[
            ],
            options={
                'verbose_name': '🔥 Hero Приложение',
                'verbose_name_plural': '🔥 Hero Баннер (Топ)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps_store.telegramapp',),
        ),
        migrations.CreateModel(
            name='WeeklyAppProxy',
            fields=[
            ],
            options={
                'verbose_name': '🏆 Weekly Приложение',
                'verbose_name_plural': '🏆 Выбор недели',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps_store.telegramapp',),
        ),
        migrations.AlterModelOptions(
            name='telegramapp',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Все приложения'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='🔥 В Hero баннер'),
        ),
        migrations.AlterField(
            model_name='telegramapp',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='🏆 В выбор недели'),
        ),
    ]
