# Generated by Django 5.2.8 on 2025-12-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0008_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на категорию (Донор)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_store.category', verbose_name='В какую категорию класть?')),
                ('target_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_store.subcategory', verbose_name='В какую подкатегорию?')),
            ],
            options={
                'verbose_name': '🤖 Источник парсинга',
                'verbose_name_plural': '🤖 Источники парсинга',
            },
        ),
    ]
