# Generated by Django 5.2.8 on 2025-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0009_parsingsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название канала (для себя)')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка (https://t.me/...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Источник Telegram (Real-Time)',
                'verbose_name_plural': 'Источники Telegram (Real-Time)',
            },
        ),
    ]
